### ISSUE TITLE
Provide more options for the design

### ISSUE THREAD

**Issue by vebaev** [covidpass-org/covidpass#30] opened 2021-07-04 12:12 UTC
Please provide more colour options, for example like the green on the webpage and more pastel colours.

Also should be an option to extract the name of the person in latin as for example now my pass contain my original name which is in Cyrillic and cannot be read in most of the EU countries :)

**Comment by RJVB** [comment] 2021-07-11 15:56
To piggyback on this issue: I would like to see an option to:

- show only the wearer's name, date of last vaccination and the number of vaccinations
- print them using a smaller font and move them below the QR code
- increase the QR Code size to make the most of the available space. I am a bit concerned that its current size could be too small on smaller-screen devices like the iPhone SE.

I don't think there's much use for printing the date of birth or the vaccine used; anyone who needs this info will be able to get it from the QR code.

But thanks for the great work, it's a shame all national don't have a feature to add the latest pass to the platform wallet so your work really fills a void!

**Comment by marvinsxtr** [comment] 2021-07-11 16:02
@RJVB Unfortunately, the second and third point are not possible due to the limitations of Apple Wallet Passes (see [this developer guide](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html)).

**Comment by RJVB** [comment] 2021-07-11 16:21
I see. Rather stupid that they haven't foreseen bigger and more complex QR codes!

**Comment by 10Meisterbaelle** [comment] 2021-07-22 10:28
I think you should also be able to choose a custom name and logo for your certificate

**Comment by mackonsti** [comment] 2021-07-22 13:18
Hello @marvinsxtr thank you very much for your excellent work.

Just like @vebaev my name is displayed in the Greek language and I have problems local authorities linking it to my passport (where my name features in both Latin and Greek alphabets) so please is there any way into selecting either name to show OR get the Latin-alphabet name? I am not sure if there is in the EU specifications such a different field for localised and international storage of the name?

Moreover, despite writing the country of issue in the rear, could we possibly also get it mentioned in the front so authorities see it immediately and confirm with the passport too?

Is there any more space of extra line(s) of text under VACCINE and DATE OF BIRTH to add e.g. "EU MEMBER STATE" label for the country?

Finally is there any idea about clearly showing this is indeed the "EU Digital COVID Certificate" as per https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en ? Can we ask to change the CERTIFICATE TYPE text appearing from "Vaccination" to "EU Digital COVID Certificate" in 2 text lines?

Many thanks, Vielen Dank!

**Comment by marvinsxtr** [comment] 2021-07-22 16:06
@10Meisterbaelle Unfortunately, it is not allowed to change the pass "trademark" according to the Apple Developer Guidelines.

**Comment by marvinsxtr** [comment] 2021-07-22 16:19
@mackonsti The name problem should be easily addressed by using the romanized version which is provided in the certificate payload. The only catch is that it is in CAPS, which results in problems e.g. with special last name suffixes. In general, I would like to keep extra options at a minimum in order to keep it simple.

I don't think there is space for any extra text. Also see the screenshot below.

The certificate type text is up for debate, I also think that it is not optimal the way it is. But there has to be some kind of indication that it is a vaccination certificate as we also support test and recovery certificates. I really like that you can see which type it is at a glance in the wallet instead of having to open every certificate.

![grafik](https://user-images.githubusercontent.com/24621914/126672919-55943a16-b991-4112-8e44-98ec82dd554e.png)

**Comment by vebaev** [comment] 2021-07-22 16:27
I think most urgent is the name, probably for Greeks and Bulgarian people :) as we have different alphabets :)

**Comment by mackonsti** [comment] 2021-07-22 21:42
Hello @marvinsxtr thank you very much for your responsiveness. My quick feedback:

> I also think that it is not optimal the way it is. But there has to be some kind of indication that it is a vaccination certificate

1. You are correct and I support you. BUT in this case, as we are talking about using the Wallet item for officials to scan it e.g. airports or other major venues, I would stick to its official title "EU Digital COVID Certificate" as per https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en otherwise indeed, something like "EU COVID Vaccination Certificate" (in 2 lines) would be more logical.

Nevertheless, can "EU Digital COVID Certificate" be in 2 lines e.g. `EU Digital COVID<br>Certificate` o `EU Digital COVID<br>Vaccination Certificate` ?

2. As @vebaev who is correct, for non Latin alphabets, the most urgent is to use "the romanized version which is provided in the certificate payload" which I am not aware it exists. However, don't be mistaken: Even for the Greek alphabet names (which myself and my wife have converted via your app) we get ALL CAPS anyway even in Greek, so do not be worried about "the only catch is that it is in CAPS" because even for the localised name, it's in CAPS anyway 😆 🤣 

I cannot show you a screenshot but trust me it's there (thankfully in 2 lines as my name has 2 long words) even with a stupid comma "," character between them <facepalm>

So this quick fix would be **totally** appreciated, perhaps a drop-down list of 2 options e.g. "Localised" or "Original" name or "Original Alphabet" and "Romanized" or "Latin Alphabet" if such field is detected.

3. Finally a small other question: On my certificate, I get the (unexpected) name `Spikevax (previously COVID-19 Vaccine Moderna)` as per https://www.ema.europa.eu/en/medicines/human/EPAR/spikevax-previously-covid-19-vaccine-moderna

For some reason (not known to me as I don't know the specs of Wallet items) the name under VACCINE is compressed to take the same space and is not legible, compared to the date numerals on the other side.

So again, is there space to have this specific name appearing in 2 lines e.g. `Spikevax (previously<br> COVID-19 Vaccine Moderna)` ?

Wallet is small already, and such fine-print are totally not visible to the average eye 😄 

Vielen Dank! Konsti

**Comment by mackonsti** [comment] 2021-07-22 22:03
P.S. Also I see the disclaimer text of yours "This certificate is only valid in combination with the ID card of the certificate holder and expires one year + 14 days after the last dose. The validity of this certificate was not checked by CovidPass." is there is an expiration date indeed? There is no mention on your website (app).

May I thus suggest the following additional text (that you have already) as I work for IT and legal people?

`Add your EU Digital COVID Certificates to your favorite wallet apps. On iOS, please use the Safari Browser and remember to allow Safari to access the camera (phone Settings → Safari). N.B. The certificate generated expires one year + 14 days after the date of the last dose!`

Best regards.

**Comment by RJVB** [comment] 2021-07-23 08:44
I've been musing about the need for an ID, which is a legal problem in (at least) France where only the national police is allowed to ask for and check official ID documents. Restaurant owners already managed to get out from under this part already, and now only need to check if the certificate is valid (to the best of my knowledge).

It's really a blooper from the EU not to have thought of adding a photo to the official certificate. Of course that would be hard to add in the wallet version... but there's a way out from that. Two actually:

- write an app that shows the information as it should, with a widget to display it on the lock screen

- generate an image (or multiple images) of the appropriate dimensions and content via your website. There are apps in the Apple store that allow you to display image(s) of choice on the lock screen so this approach would not require getting an app into the store.

I'm getting the impression that the required know-how and maybe even pre-requisites (paying Apple dev certificate to get apps in to their store) could well be present among the users you've been attracting.

PS: I don't get the argument about Apple not allowing changes to the TM field. Do they check the file you generate, and even if so, what stops you from just using a new TM instead of changing an existing one?

**Comment by mackonsti** [comment] 2021-07-24 10:52
Hi @marvinsxtr I can understand that you may be busy and have little time available for this great project, among other developers helping, can we kindly ask you if you will have time to approve and push the following changes?

* Improve the "Vaccination" name to something like "EU Digital COVID Vaccination Certificate" ? (hopefully 2 lines)
* Add per my suggestion a tip to users to enable camera access in Safari? (see above)
* At least confirm to us non-Latin-based users that the QR code indeed contains a "Romanised" version of the name (in Greek or Cyrillic) since **you have studied** the specs of the QR structure? Adding as an option to covidpass.marvinsextro.de can be done via a new Issue that I can post here, if it is more convenient for you...

Vielen Dank! Thanks for all your contributions, everyone. Tschuss

**Comment by marvinsxtr** [comment] 2021-07-24 12:22
@mackonsti I already confirmed that there is a romanised version and would implement this by checking the non romanized name for special characters and then using the romanized one as a fallback. This way we don't need an extra option.

**Comment by mackonsti** [comment] 2021-07-24 12:54
Thank you @marvinsxtr appreciate it.

**Comment by marvinsxtr** [comment] 2021-07-25 00:46
As most of the mentioned points are now fixed, I will close this for now. Feel free to open new individual issues for topics which were not addressed yet.

**Closed by marvinsxtr** 2021-07-25 00:46 UTC
Labels: enhancement
