### ISSUE TITLE
Watch wallet crashes

### ISSUE THREAD

**Issue by marban** [covidpass-org/covidpass#22] opened 2021-06-30 06:53 UTC
After adding and viewing the QR code once on the Watch, the Wallet app (I.e. Apple Pay) crashes as soon as I launch it via double-tap on the side button. Removing the QR pass + killing the Wallet app on the Watch resolves the problem.

**Comment by hauketoenjes** [comment] 2021-06-30 08:06
Hi, on what Apple Watch generation and what version of watchOS does this happen?

**Comment by marban** [comment] 2021-06-30 15:45
All Latest Gens S6 / Mini 12 / 14.6

**Comment by hauketoenjes** [comment] 2021-07-01 12:17
Ok, that is interesting. I'm on an iPhone 11 with an Apple Watch S6 on the latest stable IOS / watchOS release and I cannot reproduce the problem.  

Maybe anyone else can?

**Comment by SoerenBusse** [comment] 2021-07-01 12:22
Does your vaccination certificate contain any special characters, which may lead to a crash due to wrong encoding? However characters like "ö" like in my name, which aren't ASCII but ISO-8851-1 works absolutely fine.

**Comment by hauketoenjes** [comment] 2021-07-01 12:37
I just looked a bit through the Apple Communities and this seems to be a known Problem on some Phones / Watches. 

Discussion: https://discussions.apple.com/thread/251932786

The only solution seems to be resetting the phone / watch and re-pairing it. However, I don't think that this Problem is related to this repository, but to Apple's Wallet App on the Watch.

**Comment by marvinsxtr** [comment] 2021-07-09 14:06
Closing this issue as it does not seem to be related to CovidPass.

**Closed by marvinsxtr** 2021-07-09 14:06 UTC
Labels: help wanted, not reproducible, question
