### ISSUE TITLE
Pass only in Wallet of iPhone not in Watch visible

### ISSUE THREAD

**Issue by betamax65** [covidpass-org/covidpass#31] opened 2021-07-08 07:53 UTC
Hello,

I have now tried 2x to create my CovidPass using the website. Once I used a PDF, the other time I scanned the QR code with the camera. With both attempts, only the result was visible in the wallet of the iPhone, but not on the Watch.
iPhone 12 Pro Max with iOS 14.6 and Apple Watch Series 5 with WatchOS 7.5

The iPhone and Apple Watch were on the same Wi-Fi network. Only one other card (VIMPay) is stored in the Wallet. (and yes I tried to make anything else visible by wiping or turning the crown).
Best regards
Kai

**Comment by betamax65** [comment] 2021-07-08 08:05
Addendum: I tried to fix the problem by quitting and restarting Wallet on the Watch, that didn't work any more than a complete restart of the Watch. The pass is still only visible in the wallet on the iPhone.

**Comment by kevingrabher** [comment] 2021-07-08 09:40
Are you opening the Wallet app from menu or with double-pressing the side-button?
(for me the pass only shows when opening from menu)

**Comment by betamax65** [comment] 2021-07-08 11:15
> Are you opening the Wallet app from menu or with double-pressing the side-button?
> (for me the pass only shows when opening from menu)
I have tried both double-clicking on the sidebar and calling the Wallet app. With both methods the result is the same. It is not visible.

Best regards
Kai

**Comment by marvinsxtr** [comment] 2021-07-09 14:03
This issue does not seem to be caused by CovidPass but rather by the OS or iCloud sync. Closing this for now.

**Closed** 2021-07-09 14:04 UTC
Labels: not reproducible
