### ISSUE TITLE
Covid Certificate not readable on Apple Watch

### ISSUE THREAD

**Issue by ghost** [covidpass-org/covidpass#170] opened 2022-02-20 08:17 UTC
On the Apple Watch Series 7 the Covid Certificate is not readable since the corners are cut off. Would it be possible to resize the QR-Code for it to be fully displayed on the watch-face?

**Comment by marvinsxtr** [comment] 2022-02-26 16:21
Duplicate of #132

**Closed as completed** 2022-02-26 16:21 UTC
