### ISSUE TITLE
QR code support for everyone 

### ISSUE THREAD

**Issue by bore4k** [covidpass-org/covidpass#94] opened 2021-09-02 07:38 UTC
Hello, a Turkish guy here. 

Our vaccination program started like a month (or two). And the government is about to make vaccination mandatory for almost everywhere. They are checking it manually and It's takes a lot of time. And this is not caused because check system, It's about people whom being checked. They are unlocking their phones, opening the Government Health App (which doesn't have support for Wallet Apps), find the Vaccination Certificate and being checked. That's why there is usually a queue in front of the stores. And in these days being in crowd is not a good idea.

So, I was wondering do you have any plans to support Turkey's, even international, QR codes.

That would be so good for anyone not lives in EU :D

Thanks for your work man...

**Comment by bore4k** [comment] 2021-09-02 07:39
I know a little bit of programming and I can help you with translation.

**Comment by bore4k** [comment] 2021-09-02 07:40
I know a little bit of programming I'll do what I can and I can help you with translation.

**Comment by JantsoP** [comment] 2021-09-06 14:14
Basically dupe of #92

**Closed** 2021-11-11 11:39 UTC
