### ISSUE TITLE
QR upload not working on iOS 14.4.2

### ISSUE THREAD

**Issue by feeadftth** [covidpass-org/covidpass#150] opened 2022-01-03 22:43 UTC
Don't know if anyone else is having this issue but the buttons to either select a file from the device or open the camera are not working, no matter the browser used, on my iPhone X with iOS 14.4.2.
It's been like that for at least a week now.

**Comment by marvinsxtr** [comment] 2022-01-03 23:02
Duplicate of #35

**Closed** 2022-01-03 23:02 UTC
