### ISSUE TITLE
Accept other formats than pdf, direct access to camera and gallery

### ISSUE THREAD

**Issue by ezadoo** [covidpass-org/covidpass#1] opened 2021-06-27 12:08 UTC
I don't have a certificate myself but I testet your solution with an demo code and it works like a charme.

But I think it is a bit complicated to have to convert the image of the qr-code into pdf before you can use it.

I've looked a bit into the code, but I'm not really an expert with js, but it looks like the pdf is rendered and then processed as image, so i think it should be possible to use images in the first place.

And so the select element should be changed to allowing all 3 options (gallery, camera, files-app) too.

This would be a good improvement and simplify the use of covidpass.

**Comment by marvinsxtr** [comment] 2021-06-27 12:17
This feature is definitely on the TODO list. The image option should be quite simple to implement.

For the live camera feed, I would probably need help too.

**Comment by ezadoo** [comment] 2021-06-27 12:53
I know there are live qr-code readers for js, this could be a nice addition too, but would probably be a good amount of work, but wasn't directly what I meant.

The native file input for iOS has 3 options: photo library, take photo and browse. So you can take a photo and use it directly.

**Comment by marvinsxtr** [comment] 2021-06-27 13:28
Thank you for letting me know. In most cases I would even prefer the native way over a live feed because it would be hard to integrate into the layout.

**Comment by marvinsxtr** [comment] 2021-06-30 09:35
We implemented the option to select PDF and PNG files from the file browser in #19. Taking a picture in the native file selector does not work at high resolutions and on newer devices, but the QR code can now be scanned directly with a camera view in the browser.

**Comment by ezadoo** [comment] 2021-06-30 16:06
I've tried the live camera thing and it didn't recognize my QR Code. 
I can only test with the official demo certificate, maybe that's the reason, but the png and pdf upload with the same code are working fine.

**Comment by marvinsxtr** [comment] 2021-06-30 18:30
You need to get pretty close to the QR code for it to recognize it at the moment, maybe we should add a frame where the QR code should be aligned. Also, the reason for multiple options is that some work better than others with different devices, so this could have multiple reasons like resolution etc. Feel free to leave your experiences with the new options in this issue as we try to improve them.

**Comment by marvinsxtr** [comment] 2021-06-30 18:39
I got told that the camera view does not work on iPhone 5 with Safari, maybe someone with this device can reproduce this?

**Comment by marvinsxtr** [comment] 2021-07-09 14:00
I don't think we will fix the problem with picking files directly from camera as there are good alternatives (e.g. taking a picture in the camera app beforehand and choosing it as a file). For device specific issues, we would open new issues as they arise. Closing this for now.

**Closed by marvinsxtr** 2021-07-09 14:00 UTC
Labels: enhancement, good first issue, priority:highest

**Comment by dorianbayart** [comment] 2021-08-18 08:15
Hi,
With an iPhoneSE 2015 on iOS Beta 15, the camera doesn't start through Safari.
With Brave it starts and the QRCode is recognized. 
Don't know if I can help you another way ?
