### ISSUE TITLE
“Dose 3/2” displayed after third dose of vaccine

### ISSUE THREAD

**Issue by ilorenzom** [covidpass-org/covidpass#120] opened 2021-11-11 13:55 UTC
I just received the third dose of my pfizer vaccine and a new green pass. Now when I create the wallet certificate it says “Dose 3/2”. Is it possible to change the value on the right to the correct number?

**Comment by marvinsxtr** [comment] 2021-11-11 14:42
Duplicate of #117

**Closed** 2021-11-19 15:16 UTC
Labels: enhancement, discussion
