### ISSUE TITLE
QR code scan on iOS not working

### ISSUE THREAD

**Issue by fhibler** [covidpass-org/covidpass#154] opened 2022-01-06 08:52 UTC
Hi,

I've been trying to scan the QR code of my COVID certificates with the 'Start Camera' function - but nothing is happening.

iPhone X
iOS 15.2
Latest Safari w/ default settings

Can provide a video or any further details, if helpful.

**Comment by dariolr** [comment] 2022-01-09 13:08
same

**Comment by JantsoP** [comment] 2022-01-10 13:15
Dupe of #35

**Closed** 2022-01-10 13:16 UTC
