### ISSUE TITLE
Help Doesen't Work

### ISSUE THREAD

**Issue by GMably** [covidpass-org/covidpass#160] opened 2022-01-12 16:57 UTC
Hi, I have a problem, on the site https://covidpass.marvinsextro.de/ from my iPhone 12Mini iOS 14.3 and Safari version 14.0.2 https://www.whatsmybrowser.org/b/HFVIU 

Nothing works, the function to take the photo does not work, also the function to choose a file. And even more I cannot choose the color.

 In addition I can do nothing, Safari's options are of course authorized access to the camera and this I do not understand is given that I have used this project in the past (End July 2021). 
I even tried with Opera and Duckduckgo but without results.

 I look forward to your return, my most sincere Gauvain greetings

**Comment by marvinsxtr** [comment] 2022-01-12 17:38
Duplicate of #35

**Closed as completed by marvinsxtr** 2022-01-12 17:38 UTC
