### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by FrancescoBonizzi** [covidpass-org/covidpass#116] opened 2021-10-26 12:20 UTC
![image](https://user-images.githubusercontent.com/11348479/138877157-9849c74d-a8d6-4727-851d-73fec19a481f.png)

Hi! I get this error when using the application from my computer (I just wanted to see the output of the wallet file)! I attached also a GIF showing how to reproduce it. My browser is Edge Chromium 95.0.1020.30 64 bit.

![9nWIxOqGWK](https://user-images.githubusercontent.com/11348479/138877496-bbb79764-6e34-409e-b5e8-e4433251d0be.gif)

**Comment by JantsoP** [comment] 2021-10-31 10:26
This only works for Safari browsers on iOS. Others browsers are not supported.

**Comment by FrancescoBonizzi** [comment] 2021-10-31 13:10
Understood, thanks. Maybe you could show an error to show that!

**Comment by marvinsxtr** [comment] 2021-11-11 11:36
In this case, this is a duplicate of #76.

**Closed** 2021-11-11 11:36 UTC
