### ISSUE TITLE
QR Code Size

### ISSUE THREAD

**Issue by xDalLio** [covidpass-org/covidpass#152] opened 2022-01-04 14:16 UTC
Hi, using my pass in wallet app is fantastic, thank you so much. However I have a little issue, basically sometime the QR code is difficult to read, usually on low-end smartphones. Is it possible to make the QR code bigger or is it standard for general passes on the apple passkit? Thank you so much.

**Comment by Ein-Tim** [comment] 2022-01-04 14:39
Duplicate of #75.

**Closed** 2022-01-04 14:43 UTC
